### ISSUE TITLE
Patch to support Zip+4 US addresses

### ISSUE THREAD

**Issue by bn-ssotka** [librasteve/raku-Contact#1]
commit 5665dec79e6ad3e406b76046f1f578b26f47eabd (HEAD -> Zip-Plus-4-US)
Author: Scott Sotka <ssotka@barracuda.com>
Date:   Tue Jan 2 10:38:24 2024 -0800

    Adding support for US Zip+4 addresses

```
diff --git a/lib/Contact/Address/USA/Parse.rakumod b/lib/Contact/Address/USA/Parse.rakumod
index 06bd6a6..b191b25 100644
--- a/lib/Contact/Address/USA/Parse.rakumod
+++ b/lib/Contact/Address/USA/Parse.rakumod
@@ -23,7 +23,7 @@ class Contact::Address::USA::Parse {

         token city    { <nost-words> }
         token state   { \w ** 2 }
-        token zip     { \d ** 5 }
+        token zip     { \d ** 5 ('-' \d ** 4)? }
         token country { <whole-line> }
     }

diff --git a/t/01-usa.rakutest b/t/01-usa.rakutest
index 65ef160..1f47bc2 100644
--- a/t/01-usa.rakutest
+++ b/t/01-usa.rakutest
@@ -48,6 +48,9 @@ New York
 NY
 10003
 United States ofAmerica
+
+145 Mulberry St
+New York, NY 10013-5231
 END

 my @addresses = $addresses.split(/\n\n+/);
```

**Comment by librasteve** [comment]
hi - this looks good to me - please can you submit as a PR?

**Comment by bn-ssotka** [comment]
So, I cloned the repo locally. I created a work branch on the local repo, made the changes, committed them, then tried to push the work branch changes to github. I got the following errer:

`> git push --set-upstream origin Zip-Plus-4-US         
                                              
remote: Permission to librasteve/raku-Contact.git denied to bn-ssotka.
fatal: unable to access 'https://github.com/librasteve/raku-Contact.git/': The requested URL returned error: 403
`
Zip-Plus-4-US was the name of the working branch.

**Comment by librasteve** [comment]
sorry I do not know how to do a PR request n the command line

I would normally go fork repo on github web then
clone, change (ie. commit to main on my fork), push via the CL
then hit Contribute >> Open Pull Request back in github web

I think the 403 is a permission error since you are trying to push directly to my repo (ie not via a PR that I can review/accept/reject)  ...?

**Comment by bn-ssotka** [comment]
This would create a branch on your Repo, then I'd be able to create a PR between the 2 branches. I will try the fork repo method (never done that before)

**Comment by bn-ssotka** [comment]
I think I got it

**Comment by librasteve** [comment]
all done - thanks!
